FROM openjdk:11
ENV APP_HOME=/usr/app/
ENV test=vtest
WORKDIR $APP_HOME
COPY ./build/libs/test-0.0.1-SNAPSHOT.jar ./app.jar
COPY ./entrypoint.sh ./entrypoint.sh
RUN chmod +x entrypoint.sh
ENTRYPOINT ["/bin/sh", "-c", "./entrypoint.sh"]

#ENTRYPOINT ["java", "-jar", "app.jar","--test=$test"]